server {
    listen 80;
    server_name localhost;

    # Proxy para Reflex / Frontend
    location / {
        proxy_pass http://clearnote_reflex:3000;
    }

    # Proxy para Prefect
    location /prefect/ {
        proxy_pass http://clearnote_prefect:4200/;
    }

    # Proxy para MLflow
    location /mlflow/ {
        proxy_pass http://clearnote_mlflow:5000/;
    }
}